###############################################################################
### Core Site Configuration
###############################################################################

# Base configuration
base_url = "https://simpleminded.bot"  # do NOT include a trailing slash
title = "SimpleMindedRoBot"
compile_sass = true
minify_html = true
build_search_index = true
generate_feeds = true

# Taxonomies configuration
taxonomies = [
    {name = "tags", feed = true},
    {name = "series", feed = true}
]

###############################################################################
### Search Configuration
###############################################################################

[search]
index_format = "elasticlunr_json"
include_title = true        # include title of page/section in index
include_description = true  # include description of page/section in index
include_content = true      # include rendered content of page/section in index

###############################################################################
### Markdown Processing Configuration
###############################################################################

[markdown]
highlight_code = true
highlight_theme = "material-dark"
extra_syntaxes_and_themes = ["syntaxes"]
bottom_footnotes = true          # adds footnote backreference
render_emoji = false
external_links_target_blank = true  # rel="noopener"
external_links_no_follow = true     # rel="nofollow"
external_links_no_referrer = true   # rel="noreferrer"
smart_punctuation = true            # `...` to `…`, `"quote"` to `"curly"` etc

###############################################################################
### Site Extra Configuration
###############################################################################

[extra]
# Core Settings
language_code = "en"
author = "Scot Campbell"
author_name = "Scot Campbell"
author_job_title = "AI Consultant"
author_url = "/about"
default_language = "en"
default_section = "Blog"

# Organization Info
org_founded = "2023"
org_social_links = [
    "https://github.com/simplemindedbot",
    "https://linkedin.com/company/scotcampbell"
]
content_license = "All Rights Reserved"
site_alternative_name = "SMR"

# Content Settings
proficiency_level = "Beginner"  # or "Intermediate" or "Expert"
dependencies = [
    "ChatGPT",
    "Claude",
    "Gemini",
    "Python",
    "Zola"
]
thumbnail_width = "1200"
thumbnail_height = "630"

# Layout Configuration
toc = true                    # Table of Contents
recent = true                 # TOC / index
recent_items = 6              # Number of recent items to display
series = true                 # Enable series functionality
series_items = 0              # Max items in series list, 0 to disable
Series_parts = "Topic Series"

# Header/Footer Settings
headhr = true                 # Show horizontal rule below header
foothr = true                 # Show horizontal rule above footer
sitedesc = true              # Show site description below logo
footer_size = "s80"          # Size of copyright and powered by text
footer_credit = true
copyright = true             # Enable copyright display
copyright_override = '© $CURRENT_YEAR $SITE_TITLE • All rights reserved.'

# Logo Configuration
logo = { file="logo.png", alt="SimpleMindedRoBot" }

# Meta Display Settings
meta_index = { position="bottom", size="s90", author=false, readtime=false, readstring="min", date=false, updated=false, categories_tags=true, divider="" }
meta_post = { position="top", size="s95", author=true, readtime=false, readstring="min read", date=false, updated=true, categories_tags=true, divider="" }

# Navigation Settings
hide_section_dates = true
hide_page_nextprev_titles = false
title_size_index = "s85"

# SEO and Meta Tags
title_separator = "|"
title_addition = "Insights on AI, Agile workflows, and tech advancements."
keywords = "AI in Agile Development, AI in Project Management, Agentic AI in Software Development, AI Panel of Experts, Predictive Technologies for Agile, AI and Anthropology in the Workplace, Fintech AI Solutions, Writing User Stories with AI, AI-enhanced Software Development, Agile Transformation with AI, AI-driven Project Governance, AI Use Cases in Software Development, Hugo Static Site Development, Zola Static Site Generator, Static Site Generators for Blogs, Markdown-based Blogging, Minimalist Blogging Platforms, Content-focused Blogging, Eleventy vs Hugo for Developers, Best practices for writing user stories with AI, Using AI to improve software project management, How to use AI for writing business requirements documents, Responsive design with Zola or Hugo static sites, Managing static sites with Cloudflare Pages, AI-driven insights for agile software timelines, Setting up responsive images in Zola, Simplifying CSS with Zola for blogging, Simpleminded.bot blog, AI for Agile transformation, AI Panel of Experts for Software Projects, Static blogging platforms comparison, Simpleminded.bot series posts"
banner = "smbanner.png"
twitter_meta = "simplemindedbot"
seo = true

# Resource Configuration
uglyurls = false             # Generate full path URLs if true
integrity = false            # Enable integrity checks
js_bundle = true            # Bundle JavaScript files
search_library = "elasticlunr"
stylesheets = ["custom.css", "abridge.css"]
webmanifest = "manifest.min.json"

# JavaScript Features
js_copycode = true          # Enable code block copy button
js_email_encode = true      # Enable email obfuscation
js_prestyle = true         # Preload FontAwesome, Katex, Google Fonts
js_switcher = false        # Enable light/dark mode switcher
js_switcher_default = "light"

# PWA Configuration
pwa = true
pwa_VER = '4.0.8'
pwa_NORM_TTL = 86400       # Cache regular content for 1 day
pwa_LONG_TTL = 604800      # Cache media/assets for 1 week
pwa_TTL_NORM = '"sw.min.js", "sw_load.min.js"'
pwa_TTL_LONG = '"jpg", "jpeg", "png", "gif", "webp", "avif", "ico", "svg", "xsl", "txt"'
pwa_TTL_EXEMPT = '"js", "css", "otf", "eot", "ttf", "woff", "woff2", "mp4", "webm", "mp3", "ogg"'
pwa_cache_all = true
pwa_BASE_CACHE_FILES = "'/js/theme.min.js','/js/theme_light.min.js','/abridge.css','/js/abridge.min.js','/','/404.html','/offline/','/manifest.min.json', '/custom.css'"
pwa_IGNORE_FILES = ["_headers","sw.min.js","sw.js"]

# Navigation Menus
menu = [
    {url = "about", name = "About", slash = true, blank = false, size="s110"},
    {url = "contact", name = "Contact", slash = true, blank = false, size="s110"},
    {url = "archive", name = "Archive", slash = true, blank = false, size="s110"},
    {url = "series", name = "Series", slash = true, blank = false, size="s110"},
]

menu_footer = [
    {url = "about", name = "About", slash = true, blank = false, size="s90"},
    {url = "contact", name = "Contact", slash = true, blank = false, size="s90"},
    {url = "disclaimer", name = "AI Disclaimer", slash = true, blank = false, size="s90"},
    {url = "privacy", name = "Privacy", slash = true, blank = false, size="s90"},
    {url = "sitemap.xml", name = "Sitemap", slash = false, blank = true, size="s90"}
]

# Social Media Links
feed = true
mail = "admin@simpleminded.bot"
mastodon = "https://techhub.social/@simplemindedbot"
kofi = "simplemindedbot"
twitter = "simplemindedbot"
linkedin = "scotcampbell"
github = "simplemindedbot"
github_url = "https://github.com/simplemindedbot"
linkedin_url = "https://www.linkedin.com/in/scotcampbell"
mastodon_url = "https://mastodon.social/@simplemindedbot"
medium_url = "https://medium.com/@simplemindedbot"

# Icons
icon_top = "svgs svgh angu"  # Back to Top Button

# Mermaid Configuration
mermaid = true
mermaidurl = "https://cdn.jsdelivr.net/npm/mermaid@11.4.0/dist/mermaid.min.js"

###############################################################################
### Commented Out Options (Reference)
###############################################################################

# Core Options
#theme = "abridge"
#feed_filename = "atom.xml"
#output_dir = "public"
#ignored_content = ["*.{graphml,xlsx}", "temp.*"]
#hard_link_static = false
#ignored_content = []
#ignored_static = ["apple-touch-icon.png","banner.png","safari-pinned-tab.svg","favicon*","m*.png","android-chrome*png"]

# Security Options
#security_header_referrer = "strict-origin-when-cross-origin"
#security_header_csp = "default-src 'none'; object-src 'none'; base-uri 'self'; manifest-src 'self'; connect-src 'self'; form-action 'self'; script-src 'self'; img-src 'self' data: cdn.cloudflare.com; frame-src 'self' www.youtube-nocookie.com player.vimeo.com; media-src 'self' data: cdn.cloudflare.com www.youtube-nocookie.com player.vimeo.com; font-src 'self' cdn.cloudflare.com cdn.jsdelivr.net fonts.gstatic.com; style-src 'self' cdn.cloudflare.com cdn.jsdelivr.net fonts.googleapis.com;"

# Font Options
#fonts = [ {url = "https://fonts.googleapis.com/css?family=Roboto:400,700,italic|Roboto+Mono:400,italic"} ]
#fonts = [
#    {url = "fonts/Roboto-Mono.woff2"},
#    {url = "fonts/Roboto-Mono-Italic.woff2"},
#    {url = "fonts/Roboto.woff2"},
#    {url = "fonts/Roboto-Italic.woff2"},
#    {url = "fonts/Roboto-Bold.woff2"},
#]

# KaTeX Options
#katex_options = "js/katexoptions.js"
#katex_bundle = "js/katexbundle.min.js"
#katex_css = "katex.min.css"
#katex_js = "js/katex.min.js"
#mathtex_js = "js/mathtex-script-type.min.js"
#katex_autorender_js = "js/katex-auto-render.min.js"
#katex_css = "https://cdn.jsdelivr.net/npm/katex@0.15.6/dist/katex.min.css"
#katex_css_integrity = "sha384-ZPe7yZ91iWxYumsBEOn7ieg8q/o+qh/hQpSaPow8T6BwALcXSCS6C6fSRPIAnTQs"
#katex_js = "https://cdn.jsdelivr.net/npm/katex@0.15.6/dist/katex.min.js"
#katex_js_integrity = "sha384-ljao5I1l+8KYFXG7LNEA7DyaFvuvSCmedUf6Y6JI7LJqiu8q5dEivP2nDdFH31V4"
#katex_autorender_js = "https://cdn.jsdelivr.net/npm/katex@0.15.6/dist/contrib/auto-render.min.js"
#katex_autorender_js_integrity = "sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR"
#mathtex_js = "https://cdn.jsdelivr.net/npm/katex@0.15.6/dist/contrib/mathtex-script-type.min.js"
#mathtex_js_integrity = "sha384-jiBVvJ8NGGj5n7kJaiWwWp9AjC+Yh8rhZY3GtAX8yU28azcLgoRo4oukO87g7zDT"
#math = false
#math_auto_render = false

###############################################################################
### Commented Out [extra] Options (Reference)
###############################################################################

# Menu and Navigation Options
#arrow_pagination = true

# Footer Options
#footer_credit_override = '<p class="s90">Powered by <a href="https://www.getzola.org/" target="_blank">Zola</a> &#38; <a href="https://github.com/Jieiku/abridge/" target="_blank">Abridge</a></p>'
#archive_reverse = true

# Logo Options
#textlogo = '<font color="#f90">A</font>bridge'

# Meta/SEO Options
#google = "Your Google Site verification code."
#bing = "Your Bing Site verification code."
#dev = false
#head_extra = '<meta name="analytics" content="my-analytics-id" /><meta name="advertising" content="my-advertising-id" />'

# Social Media Options
#element = "matrix.example.com"
#buymeacoffee = "your-user-name"
#discord = "your-discord"
#facebook = "your-user-name"
#gitlab = "your-user-name"
#codeberg = "your-user-name"
#github_sponsor = "your-user-name"
#bitbucket = "your-user-name"
#python = "your-user-name"
#docker = "your-user-name"
#stack = "your-user-name"
#instagram = "your-user-name"
#pixelfed = "https://pixelfed.example.com/"
#pinterest = "your-user-name"
#twitch = "your-user-name"
#youtube = "channel/your-channel-id"
#peertube = "https://peertube.example.com/@username"
#researchgate = "your-profile-id"
#telegram = "your-user-name"

# Icon Options
#icon_search = "svgs svgm search"
#icon_adjust = "svgs adjust"
#icon_first = "svgs svgh angll"
#icon_prev = "svgs svgh angl"
#icon_next = "svgs svgh angr"
#icon_last = "svgs svgh angrr"
#icon_read = "svgs fa-solid fa-glasses"
#icon_date = "svgs fa-solid fa-calendar"
#icon_info = "svgs fa-solid fa-circle-info"
#icon_author = "svgs fa-solid fa-pen-fancy"
#fontawesome = "https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.1.1/css/all.min.css"

# Favicon Options
#favicon_theme_color = "#333333"
#favicon_ms_color = "#333333"
#favicon_mask = "safari-pinned-tab.svg"
#favicon_mask_color = "#000000"
#favicon_svg = "favicon.svg"
#favicon180 = "apple-touch-icon.png"
#favicon32 = "favicon-32x32.png"
#favicon16 = "favicon-16x16.png"

# Comments Options
#comments.hyvor = "9366"
#comments.hyvorcolor = "os"
#comments.disqus = true
