[build]
publish = "public"
command = "npm run abridge -- '--base-url https://simpleminded.bot'"
functions = "netlify/functions"

[build.environment]
ZOLA_VERSION = "0.19.2"
NODE_VERSION = "22.9.0"

[context.deploy-preview]
command = "npm run abridge -- '--drafts --base-url https://simpleminded.bot'"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
  baseUrl = "https://simpleminded.bot"
  sitemapPath = "/sitemap.xml"
  ignorePeriod = 0
  providers = [
    "google",
    "yandex"
  ]

[functions]
  node_bundler = "esbuild"
