[build]
publish = "public"
command = "npm run abridge -- '--base-url https://simpleminded.bot'"
functions = "netlify/functions"

[build.environment]
ZOLA_VERSION = "0.19.2"
NODE_VERSION = "22.9.0"

[context.deploy-preview]
command = "npm run abridge -- '--drafts --base-url https://simpleminded.bot'"

[[plugins]]
  package = "@netlify/plugin-csp-nonce"
  [plugins.inputs]
  reportOnly = true
  excludedPath = [
    "/api/*",
    "**/*.bespoke.extension"
  ]

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
	baseUrl = "https://simpleminded.bot"
	sitemapPath = "/sitemap.xml"
	ignorePeriod = 0
	providers = [
		"google",
		"yandex"
	]

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = """
      default-src 'self';
      script-src '{{nonce}}' 'strict-dynamic' 'unsafe-inline' 'self'
        'unsafe-eval'
        https://*.cloudflareinsights.com
        https://*.cloudflare.com
        https://static.cloudflareinsights.com;
      script-src-elem '{{nonce}}' 'strict-dynamic' 'unsafe-inline' 'self'
        'unsafe-eval'
        https://*.cloudflareinsights.com
        https://*.cloudflare.com
        https://static.cloudflareinsights.com;
      script-src-attr 'unsafe-inline';
      style-src 'self' 'unsafe-inline' 
        https://fonts.googleapis.com;
      font-src 'self' 
        https://fonts.gstatic.com;
      connect-src 'self' 
        https://*.cloudflareinsights.com 
        https://fonts.googleapis.com 
        https://fonts.gstatic.com;
      img-src 'self' data: https:;
    """