[build]
publish = "public"
command = "npm run abridge -- '--base-url https://simpleminded.bot'"
functions = "netlify/functions"

[build.environment]
ZOLA_VERSION = "0.19.2"
NODE_VERSION = "22.9.0"

[context.deploy-preview]
command = "npm run abridge -- '--drafts --base-url https://simpleminded.bot'"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
  baseUrl = "https://simpleminded.bot"
  sitemapPath = "/sitemap.xml"
  ignorePeriod = 0
  providers = [
    "google",
    "yandex"
  ]

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.cloudflareinsights.com https://*.cloudflare.com https://www.google.com https://*.google.com https://*.gstatic.com https://*.recaptcha.net https://cdn.jsdelivr.net 'strict-dynamic';
      script-src-elem 'self' 'unsafe-inline' 'unsafe-eval' https://*.cloudflareinsights.com https://*.cloudflare.com https://www.google.com https://*.google.com https://*.gstatic.com https://*.recaptcha.net https://cdn.jsdelivr.net 'strict-dynamic';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self' https://*.cloudflareinsights.com https://cdn.jsdelivr.net https://*.google.com https://*.doubleclick.net;
      frame-src 'self' https://*.google.com https://recaptcha.google.com;
      worker-src 'self' blob:;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'self';
      upgrade-insecure-requests;
    """