[build]
publish = "public"
command = "npm run abridge -- '--base-url https://simpleminded.bot'"

[build.environment]
ZOLA_VERSION = "0.19.2"
NODE_VERSION = "22.9.0"

[context.deploy-preview]
command = "npm run abridge -- '--drafts --base-url https://simpleminded.bot'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubdomains"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'nonce-{{nonce}}' https://cdn.osano.com https://cmp.osano.com https://platform-api.sharethis.com https://buttons-config.sharethis.com;
      style-src 'self' 'nonce-{{nonce}}' https://cdn.osano.com https://fonts.googleapis.com 'unsafe-inline';
      connect-src 'self' https://cdn.osano.com https://platform-api.sharethis.com https://l.sharethis.com;
      img-src 'self' data: https://platform-cdn.sharethis.com;
      font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net;
      worker-src 'self' blob: https://cmp.osano.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """

[[headers]]
  for = "*.js"#javascript
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"
[[headers]]
  for = "*.css"#stylesheet
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"
[[headers]]
  for = "*.svg"#image/favicon
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.png"#image/favicon
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.ico"#image/favicon
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.jpg"#image
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.jpeg"#image
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.gif"#image
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.webp"#image
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.avif"#image
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.mp4"#video
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.webm"#video
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.mp3"#audio
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.ogg"#audio
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.otf"#font
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.eot"#font
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.ttf"#font
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.woff"#font
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.woff2"#font
  [headers.values]
    Cache-Control = "public, max-age=604800"
