[build]
publish = "public"
command = "npm run abridge -- '--base-url https://simpleminded.bot'"

[build.environment]
ZOLA_VERSION = "0.19.2"

[context.deploy-preview]
command = "npm run abridge -- '--drafts --base-url https://simpleminded.bot'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubdomains"
    Permissions-Policy = "interest-cohort=(), accelerometer=(), ambient-light-sensor=(), battery=(), bluetooth=(), browsing-topics=(), camera=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(), gamepad=(), geolocation=(), gyroscope=(), hid=(), identity-credentials-get=(), idle-detection=(), magnetometer=(), microphone=(), midi=(), otp-credentials=(), payment=(), picture-in-picture=(), publickey-credentials-create=(), publickey-credentials-get=(), serial=(), storage-access=(), sync-xhr=(), usb=(), web-share=(), window-management=(), xr-spatial-tracking=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdn.osano.com https://platform-api.sharethis.com; connect-src 'self' https://cdn.osano.com https://platform-api.sharethis.com; style-src 'self' https://cdn.osano.com; img-src 'self' data: https://platform-cdn.sharethis.com; frame-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self';"

[[headers]]
  for = "*.js"#javascript
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"
[[headers]]
  for = "*.css"#stylesheet
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"
[[headers]]
  for = "*.svg"#image/favicon
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.png"#image/favicon
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.ico"#image/favicon
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.jpg"#image
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.jpeg"#image
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.gif"#image
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.webp"#image
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.avif"#image
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.mp4"#video
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.webm"#video
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.mp3"#audio
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.ogg"#audio
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.otf"#font
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.eot"#font
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.ttf"#font
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.woff"#font
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.woff2"#font
  [headers.values]
    Cache-Control = "public, max-age=604800"
