[build]
publish = "public"
command = "npm run abridge -- '--base-url https://simpleminded.bot'"

[build.environment]
ZOLA_VERSION = "0.19.2"
NODE_VERSION = "22.9.0"

[context.deploy-preview]
command = "npm run abridge -- '--drafts --base-url https://simpleminded.bot'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubdomains"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'nonce-{{nonce}}' https://cdn.osano.com https://cmp.osano.com;
      style-src 'self' 'nonce-{{nonce}}' https://cdn.osano.com https://fonts.googleapis.com;
      connect-src 'self' https://cmp.osano.com;
      img-src 'self' data:;
      font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net;
      worker-src 'self' blob: https://cmp.osano.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """

[[headers]]
  for = "*.js" # JavaScript files
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"

[[headers]]
  for = "*.css" # Stylesheets
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"

[[headers]]
  for = "*.svg" # SVG images and icons
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.png" # PNG images
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.ico" # Favicon
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.jpg" # JPEG images
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.jpeg" # JPEG images
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.gif" # GIF images
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.webp" # WebP images
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.avif" # AVIF images
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.mp4" # Video files
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.webm" # WebM video files
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.mp3" # Audio files
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.ogg" # OGG audio files
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.otf" # OpenType fonts
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for
